const productList = [
	"Apple",
	"Banana",
	"Orange",
	"Pear",
	"Strawberry",
	"Blueberry",
	"Raspberry",
	"Watermelon",
	"Pineapple",
	"Mango",
	"Avocado",
	"Tomato",
	"Cucumber",
	"Carrot",
	"Broccoli",
	"Cauliflower",
	"Spinach",
	"Lettuce",
	"Potato",
	"Sweet potato",
	"Onion",
	"Garlic",
	"Ginger",
	"Lemon",
	"Lime",
	"Chickpeas",
	"Lentils",
	"Black beans",
	"Kidney beans",
	"Quinoa",
	"Brown rice",
	"Oats",
	"Barley",
	"Buckwheat",
	"Almonds",
	"Walnuts",
	"Cashews",
	"Peanut butter",
	"Sunflower seeds",
	"Chia seeds",
	"Flaxseeds",
	"Sesame seeds",
	"Coconut milk",
	"Cow's milk",
	"Goat milk",
	"Yogurt",
	"Butter",
	"Olive oil",
	"Coconut oil",
	"Chicken",
	"Beef",
	"Pork",
	"Lamb",
	"Turkey",
	"Duck",
	"Salmon",
	"Tuna",
	"Shrimp",
	"Crab",
	"Lobster",
	"Cod",
	"Haddock",
	"Sardines",
	"Trout",
	"Mackerel",
	"Eggs",
	"Honey",
	"Maple syrup",
	"Soy sauce",
	"Vinegar",
	"Mustard",
	"Ketchup",
	"Mayonnaise",
	"Salt",
	"Pepper",
	"Cinnamon",
	"Nutmeg",
	"Basil",
	"Parsley",
	"Thyme",
	"Rosemary",
	"Oregano",
	"Cumin",
	"Paprika",
	"Turmeric",
	"Chili pepper",
	"Coriander",
	"Dill",
	"Bay leaf",
	"Vanilla extract",
	"Cocoa powder",
	"Dark chocolate",
	"Greek yogurt",
	"Cottage cheese",
	"Gouda cheese",
	"Cheddar cheese",
	"Parmesan cheese",
	"Mozzarella cheese",
	"Swiss cheese",
	"Feta cheese",
];

function getRandomPrice() {
	return (Math.random() * 10).toFixed(2); // Generate random prices between 0 and 10
}

function getRandomStarRating() {
	return (2 + Math.random() * 3).toFixed(1); // Generate random star ratings between 2 and 5
}

const products = productList.map((product, index) => ({
	id: index + 1,
	name: product,
	price: getRandomPrice(),
	img: "#",
	star_rating: getRandomStarRating(),
	discount: false,
	discount_amount: 0,
	stock: true,
	new_product: false,
}));

const jsonData = JSON.stringify(products, null, 2);

console.log(jsonData); // Output the JSON data to the console
